BEGIN;

CREATE TABLE IF NOT EXISTS stream_metadata (
  mint_id TEXT PRIMARY KEY,
  name TEXT,
  symbol TEXT,
  description TEXT,
  website TEXT,
  twitter TEXT,
  telegram TEXT,
  image_uri TEXT,
  banner_uri TEXT,
  thumbnail TEXT,
  creator_address TEXT,
  bonding_curve JSONB,
  real_sol_reserves NUMERIC,
  real_token_reserves NUMERIC,
  virtual_sol_reserves NUMERIC,
  virtual_token_reserves NUMERIC,
  ath_market_cap NUMERIC,
  ath_market_cap_timestamp TIMESTAMP,
  total_supply NUMERIC,
  is_currently_live BOOLEAN,
  nsfw BOOLEAN,
  hidden BOOLEAN,
  downrank_score NUMERIC,
  livestream_downrank_score NUMERIC,
  last_reply TIMESTAMP,
  last_trade_timestamp TIMESTAMP,
  livestream_ban_expiry TIMESTAMP,
  king_of_the_hill_timestamp TIMESTAMP,
  created_timestamp TIMESTAMP,
  metadata_uri TEXT,
  pump_swap_pool TEXT,
  raydium_pool TEXT,
  market_id TEXT,
  program TEXT,
  platform TEXT,
  hide_banner BOOLEAN,
  complete BOOLEAN,
  inverted BOOLEAN,
  updated_at TIMESTAMP DEFAULT NOW()
);

COMMIT;
